#!/bin/bash
# Quick Reference Commands for RL Training and Evaluation

echo "=================================================="
echo "  RL Autonomous Driving - Quick Reference"
echo "=================================================="
echo "TRAINING:"
echo "  # Basic training (PPO, 100k steps)"
echo "  python scripts/train.py -a ppo -t 100000"
echo ""
echo "  # Train DQN on hard difficulty with 8 parallel envs"
echo "  python scripts/train.py -a dqn -t 200000 -n 8 -d hard"
echo ""
echo "  # Train SAC with custom config"
echo "  python scripts/train.py -a sac --config config/custom.json"
echo ""
echo "EVALUATION:"
echo "  # Evaluate model (replace path with your model)"
echo "  python scripts/evaluate.py -m models/ppo_medium_20231205/final_model.zip -a ppo -n 100"
echo ""
echo "  # Evaluate with video recording"
echo "  python scripts/evaluate.py -m models/best_model.zip -a ppo --record-video --n-videos 5"
echo ""
echo "MONITORING:"
echo "  # Launch TensorBoard"
echo "  tensorboard --logdir logs/"
echo "  # Then open: http://localhost:6006"
echo ""
echo "GENERATE PLOTS:"
echo "  # Generate both learning curve and violin plot"
echo "  python scripts/generate_plots.py -l logs/ppo_medium_TIMESTAMP -r results/MODEL_TIMESTAMP/detailed_results.json"
echo ""
echo "  # Generate only learning curve"
echo "  python scripts/generate_plots.py --log-dir logs/ppo_medium_TIMESTAMP --learning-curve-only"
echo ""
echo "  # Generate only violin plot"
echo "  python scripts/generate_plots.py --results-file results/MODEL_TIMESTAMP/detailed_results.json --violin-only"
echo ""
echo "HELP:"
echo "  python scripts/train.py --help"
echo "  python scripts/evaluate.py --help"
echo "  python scripts/generate_plots.py --help"
echo ""
echo "=================================================="
